### ISSUE TITLE
Exception in get_vehicle_information()

### ISSUE THREAD

**Issue by bitzer-git** [DasBasti/pySmartHashtag#15]
Sometimes accounts.py crashes with an invalid KEY exception in get_vehicle_information() caused by 

       {"code":"1402","message":"The access token is invalid"}, status = 200

My proposal would be to checkt it 
        if "data" in r_car_info.json():
            self.vehicles.get(vin).combine_data(r_car_info.json()["data"])
        else :
            _LOGGER.warning(f"'data' not existing in {r_car_info.text}, status = {r_car_info.status_code}")
            return
and let the calling function handle the empty return value.

**Comment by DasBasti** [comment]
That should be handled by this hook: https://github.com/DasBasti/pySmartHashtag/blob/1d02791c1b715e466c34d369f94c30edb6bbb6da/pysmarthashtag/api/client.py#L80

And after relogin the request needs to be sent again. That needs to be fixed.

**Comment by DasBasti** [comment]
can you checkout the newest main branch? I changed the token refresh mechanism

**Comment by bitzer-git** [comment]
It still has problems. As far as I can see the retry just calls /remote-control/vehicle/status/ but does not restart the other steps of the login: Login Token, Access Token, API Context. 

With the following code in account.py it would work. Please check if it would make sense:

```
                except SmartAuthError:
                    _LOGGER.debug(f"Got Auth Error, retry: {retry}")
                    await self.config.authentication.login()
                    continue

```

**Comment by bitzer-git** [comment]
Just as info: It seems like the access token is only valid for 60 seconds.

**Comment by DasBasti** [comment]
This should be handles in #17 now
